ALTER TABLE beca_asignada TYPE=InnoDB;

ALTER TABLE factura TYPE=InnoDB;

ALTER TABLE factura_cliente TYPE=InnoDB;

ALTER TABLE factura_proveedor TYPE=InnoDB;

ALTER TABLE item_factura TYPE=InnoDB;

ALTER TABLE jdo_table TYPE=InnoDB;

ALTER TABLE kiosco TYPE=InnoDB;

ALTER TABLE localidad TYPE=InnoDB;

ALTER TABLE movimiento_caja TYPE=InnoDB;

ALTER TABLE oid TYPE=InnoDB;

ALTER TABLE planilla_es TYPE=InnoDB;

ALTER TABLE producto TYPE=InnoDB;

ALTER TABLE proveedor TYPE=InnoDB;

ALTER TABLE provincia TYPE=InnoDB;

ALTER TABLE sesion TYPE=InnoDB;

ALTER TABLE usuario TYPE=InnoDB;

ALTER TABLE usuario_planilla_es TYPE=InnoDB;

